---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name: ensure apache is at the latest version
    yum:
      pkg: httpd
      state: latest
