---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name: ping
    ping:
  - name: ensure apache is at the latest version
    apt:
      pkg: vim
      state: latest
      update_cache: yes
